### ISSUE TITLE
Difficult to exit / quit the use of certain selection tools

### ISSUE THREAD

**Issue by TabLand** [oriedita/oriedita#325]
I've just noticed that it's possible to get un-intuitively stuck whilst using some tools in the selection category. All of these depend on crease lines being selected in advance

<table>
<tr>
<th>Condition</th><th>Tool Name</th><th>Description </th>
</tr>
<tr><td rowspan="2">Acceptable</td><td>Move selection</td><td rowspan="2"> When no crease lines are selected prior to engaging this tool, clicking or dragging anywhere exits the tool. after which the tool is no longer highlighted in green</td></tr>
<tr><td>Copy selection </td></tr>
<tr><td rowspan="3">Needs Improvement</td><td>Four point move</td><td rowspan="3"> When no crease lines are selected prior to engaging this tool, selecting 4 vertices A,B, C and D will exit this tool (no longer highlighted in green). A quicker method is to select one vertex twice, or once then click an empty part of the canvas / crease line after which the tool is no longer highlighted in green. Clicking on an empty part of the canvas does not release the tool, nor is it possible to switch to another tool.

<br/><br/> Additionally, for <b>Four point move</b>, the documentation refers to a point G in step 3 (typo) - should refer to point C</td></tr>
<tr><td>Four point copy selection</td></tr>
<tr><td>Reflect (copy) selection along line </td></tr>

</table>

A suitable workaround for all the above would be not to engage these selection tools if no crease lines have been selected prior i.e retain previously used tool as primary (e.g how Delete selection works with empty selection), or switch to a "no-action tool". A warning sound could be played + the tool icon highlighted in amber / yellow. The help text screen could be shown as it is now. A pop-up warning dialogue stating "Please select one or more crease lines first" might be too obstructive, perhaps this could be displayed in the lower bar, or on the top left of the canvas similar to how the "Folding estimate under calculation" appears.

I'll try and submit a patch for this in the next few days.

**Comment by undertrox** [comment]
Good catch! That issue was already reported and fixed for the 2 tools in the "Acceptable" category, but we seem to have missed the other 3 tools. (Check out #275)

Iirc, the normal behavior for all these tools is that you activate them, they work once on the selection, and then get deactivated automatically. Thats also why the first 2 tools get deactivated after using them once without a selection. You could either copy that behavior to the other 3, or implement one of your proposed solutions for all 5. 

In my opinion the most intuitive would be to color the selected tool yellow and activate a no-action tool. Possibly even activate the normal selection tool to show the user that something needs to be selected.

**Comment by TabLand** [comment]
>This is because the "current selected tool" state is lost, and would we would have to start keeping tool (error) history for which there is no other additional use.

Just stumbled upon the PropertyChangeSupport / PropertyChangeEvent classes, which keep track of and share old values for MouseMode

**Comment by TabLand** [comment]
Fixed in #327
