### ISSUE TITLE
OriEdita Build Failure on Windows 10

### ISSUE THREAD

**Issue by maazashiq** [oriedita/oriedita#340]
```
Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)
Maven home: D:\\ApacheMaven\apache-maven-3.9.3
Java version: 20.0.1, vendor: Oracle Corporation, runtime: D:\Program Files\Java\jdk-20
Default locale: en_GB, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
``` 

Note: Unable to build on Windows 10

```
[ERROR] Failures:
[ERROR]   CpTest.testLoadAndSaveCpFile:31 expected: <1 200.0 200.0 200.0 -200.0
1 200.0 -200.0 -200.0 -200.0
1 -200.0 -200.0 -200.0 200.0
1 -200.0 200.0 200.0 200.0
3 200.0 200.0 0.0 0.0
2 0.0 0.0 -200.0 -200.0
> but was: <1 200.0 200.0 200.0 -200.0
1 200.0 -200.0 -200.0 -200.0
1 -200.0 -200.0 -200.0 200.0
1 -200.0 200.0 200.0 200.0
3 200.0 200.0 0.0 0.0
2 0.0 0.0 -200.0 -200.0
``` 

[build.log](https://github.com/oriedita/oriedita/files/12236845/build.log)

**Comment by TabLand** [comment]
I think this issue appears to be caused by a mismatch in line endings. The data being compared, a temporary file named export__.cp (windows line endings) and square.cp (already in repository).

Interestingly, when I clone the git repository using Git-SCM which runs on Cygwin, the line endings are all CRLF. It's when we download the source code via github's "Download zip" that line endings are messed up. I can try to submit a patch that works for all scenarios - but this will require us to discard carriage returns in both files being compared...
