### ISSUE TITLE
Hidden and inaccessible UI elements for those with small screen sizes

### ISSUE THREAD

**Issue by TabLand** [oriedita/oriedita#357]
It's not currently possible for those with small screen resolutions to see or use the entire UI, as some buttons / entire panel sections become hidden. See attached screenshot:

![image](https://github.com/oriedita/oriedita/assets/2546543/b5615f8f-4099-4312-897e-c2d1d7ba3346)

**Comment by TabLand** [comment]
Hi @undertrox,

I feel @Minh-Than's change covers half of the requirement. The top and bottom panels need to be scrollable horizontally as well...?

**Comment by Minh-Than** [comment]
Those for now are left as is partly because they'll be eventually revamped into new button placements that don't require scroll bar for even half-screen window. 
It's also because mouse wheel, while works for vertical scroll even with the vertical scroll bar set to not be visible, doesn't work for horizontal scroll and has to be have the scroll bar visible to be scrollable. Shift + mouse wheel doesn't work either unless the horizontal scroll bar is visible. I could just add in some paddings for the panel to fit in the bar but it doesn't look very nice for me.

Thought if you don't mind it or have any other suggestions do let me know.

**Comment by TabLand** [comment]
There are a few solutions I can think of from other popular applications:

- Have [<] and [>] buttons on the left and right respectively that perform the scroll action, and highlight that the toolbar is being partially displayed
- Have a hamburger menu [☰] or 3 vertical dots [⋮] that when clicked would show the options that are hidden
- Each toolbar splits into multiple rows, just like responsively designed modern webpages

Not sure what the new button placement change involves, it may already be one of these or a better solution

**Comment by Minh-Than** [comment]
@JuhoKonkkola is working on at least the major layout change so you can talk to him here or in Discord. The layout change involves dropdown buttons so one button can have multiple tools (like in photoshop). That plus the rearrangement of the buttons should be good for reducing the the busy UI to something more manageable.

**Comment by TabLand** [comment]
Grouped buttons sound like a really good solution that should reduce clutter and most likely make navigation more intuitive as well.

Happy to wait for that 🙂✌🏾

**Comment by JuhoKonkkola** [comment]
The UI redesign is going to almost halve the amount of buttons, so the ui takes less space on the screen, entire colums are removed from both sides, and the UI should fit entirely even when you are using oriedita on only on half a screen, or even redicung the size from that too. For really old monitors with 720p resolution (and windows 150% scaling), the side panels still don't fit entirely, but at least they are scrollable, and you can close many of them completely, since the most important tools will all be on left and bottom panels and hopefully in positions that doesn't need any scrolling.

For making the window even smaller than half the screen, well, I hope the UI redesign should be enough for those cases too. Improving that even more would effectively need to reduce the amount of buttons in a way that I would believe it starts to hurt the user experience, making many of the tools too difficult to reach behind all the menus. So the usability and amount of tools visible need to be balanced between it being good to use for as many people as possible and trying to cover some niche use cases of the window.
